services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - db_data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - 5433:5432

volumes:
    db_data:
